blog:
  # restart: always
  build: ./blog
  ports:
    - "8000:8000"
  links:
    - mayblog_db:mayblog_db
  # volumes:
  #   - /usr/src/app/static
  env_file: .env
  # command: /usr/local/bin/uwsgi --ini /usr/src/app/mayblog_uwsgi.ini
  # command: /usr/local/bin/uwsgi --ini mayblog_uwsgi.ini
  # command: /usr/bin/python2.7 manage.py runserver 0.0.0.0:5000
  # command: /bin/sh -c "while true; do echo hello world; sleep 1; done"



mayblog_db:
  # restart: always
  image: mysql:5.6.26
  env_file: .env
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"





