blog:
  # restart: always
  build: ./blog
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
  # volumes:
  #   - /usr/src/app/static
  env_file: .env
  # command: /usr/local/bin/uwsgi --ini /usr/src/app/mayblog_uwsgi.ini
  # command: /usr/local/bin/uwsgi --ini mayblog_uwsgi.ini
  # command: /usr/bin/python2.7 manage.py runserver 0.0.0.0:5000
  # command: /bin/sh -c "while true; do /usr/bin/python2.7 /usr/src/app/manage.py makemigrations; /usr/bin/python2.7 /usr/src/app/manage.py migrate; sleep 1; done"
  # command: /bin/sh /usr/src/app/init.sh


postgres:
  # restart: always
  image: postgres:9.4.4
  env_file: .env
  volumes:
    - /var/lib/postgres
  ports:
    - "3306:3306"





