blog:
  # restart: always
  build: ./blog
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
  # volumes:
  #   - /usr/src/app/static
  env_file: .env


postgres:
  # restart: always
  image: postgres:9.4.4
  env_file: .env
  volumes:
    - /var/lib/postgres
  # ports:
  #   - "3306:3306"





