blog:
  # restart: always
  build: ./blog
  # expose:
  #   - "8000"
  ports:
    - "8000:8000"
    # - "5000:5000"
  # links:
  #   - mysql:mysql
  volumes:
    - /usr/src/app/static
  env_file: .env
  # command: /usr/local/bin/uwsgi --ini /usr/src/app/mayblog_uwsgi.ini
  command: /usr/local/bin/uwsgi --ini mayblog_uwsgi.ini
  # command: /usr/bin/python2.7 manage.py runserver 0.0.0.0:5000
  # command: /bin/sh -c "while true; do echo hello world; sleep 1; done"


# nginx:
#   restart: always
#   build: ./nginx/
#   ports:
#     - "80:80"
#   volumes:
#     - /www/static
#   volumes_from:
#     - web
#   links:
#     - web:web

# mysql:
#   restart: always
#   image: sameersbn/mysql:latest
#   env_file: .env
#   volumes_from:
#     - data
#   ports:
#     - "3306:3306"

# redis:
#   restart: always
#   image: redis:latest
#   ports:
#     - "6379:6379"

# data:
#   restart: always
#   image: sameersbn/mysql:latest
#   volumes:
#     - /var/lib/mysql
#   command: true